<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Position;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        Employee::query()->withTrashed()->forceDelete();

        $employees = [

        // ===========================
        // DIVISI IT
        // ===========================

        [
            'division_id' => 1,
            'position_id' => 1,
            'nik' => 'EMP2026001',
            'nama_lengkap' => 'Muhammad Al Farizi',
            'email_kantor' => 'admin.alfarizi@novacore.co.id',
            'no_hp' => '08957045678',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2008-12-26',
            'alamat' => 'Bandung',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-001.000',
            'bpjs' => 'BPJS2026001',
            'tanggal_masuk' => '2023-06-13',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 1,
            'position_id' => 2,
            'nik' => 'EMP2026002',
            'nama_lengkap' => 'Marcello Aditya Putra',
            'email_kantor' => 'admin.marcello@novacore.co.id',
            'no_hp' => '085591087724',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2009-05-18',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-002.000',
            'bpjs' => 'BPJS2026002',
            'tanggal_masuk' => '2024-12-01',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
            
        ],

        [
            'division_id' => 1,
            'position_id' => 3,
            'nik' => 'EMP2026003',
            'nama_lengkap' => 'Dewi Anggraini',
            'email_kantor' => 'admin.dewi@novacore.co.id',
            'no_hp' => '08789250783',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2006-03-20',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-003.000',
            'bpjs' => 'BPJS2026003',
            'tanggal_masuk' => '2024-08-17',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 1,
            'position_id' => 4,
            'nik' => 'EMP2026004',
            'nama_lengkap' => 'Andika Pratama Ilham',
            'email_kantor' => 'admin.andika@novacore.co.id',
            'no_hp' => '08957785901',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2008-07-01',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-004.000',
            'bpjs' => 'BPJS2026004',
            'tanggal_masuk' => '2025-10-03',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        // ===========================
        // DIVISI HRD
        // ===========================

        [
            'division_id' => 4,
            'position_id' => 20,
            'nik' => 'EMP2026005',
            'nama_lengkap' => 'Alya Rahmawati',
            'email_kantor' => 'hr.alya@novacore.co.id',
            'no_hp' => '08123456789',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1997-02-27',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-005.000',
            'bpjs' => 'BPJS2026005',
            'tanggal_masuk' => '2010-01-23',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 4,
            'position_id' => 21,
            'nik' => 'EMP2026006',
            'nama_lengkap' => 'Adinda Rahmawati',
            'email_kantor' => 'hr.adinda@novacore.co.id',
            'no_hp' => '08123456789',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2000-10-30',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-006.000',
            'bpjs' => 'BPJS2026006',
            'tanggal_masuk' => '2022-06-12',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        // ===========================
        // DIVISI FINANCE
        // ===========================

        [
            'division_id' => 5,
            'position_id' => 22,
            'nik' => 'EMP2026007',
            'nama_lengkap' => 'Bima Putra',
            'email_kantor' => 'bima.finance@novacore.co.id',
            'no_hp' => '08587899403',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1995-12-25',
            'alamat' => 'Jakarta',
            'agama' => 'Kristen Protestan',
            'npwp' => '12.345.678.9-007.000',
            'bpjs' => 'BPJS2026007',
            'tanggal_masuk' => '2018-08-02',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 5,
            'position_id' => 23,
            'nik' => 'EMP2026008',
            'nama_lengkap' => 'Citra Dewi',
            'email_kantor' => 'citra.finance@novacore.co.id',
            'no_hp' => '08135049773',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1998-05-15',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-008.000',
            'bpjs' => 'BPJS2026008',
            'tanggal_masuk' => '2019-01-20',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 5,
            'position_id' => 24,
            'nik' => 'EMP2026009',
            'nama_lengkap' => 'Dimas Prasetyo',
            'email_kantor' => 'dimas.finance@novacore.co.id',
            'no_hp' => '08123456789',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1996-06-27',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-009.000',
            'bpjs' => 'BPJS2026009',
            'tanggal_masuk' => '2017-11-15',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 5,
            'position_id' => 25,
            'nik' => 'EMP2026010',
            'nama_lengkap' => 'Eka Putri',
            'email_kantor' => 'eka.finance@novacore.co.id',
            'no_hp' => '08129978045',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1997-02-26',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-010.000',
            'bpjs' => 'BPJS2026010',
            'tanggal_masuk' => '2018-08-02',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 5,
            'position_id' => 26,
            'nik' => 'EMP2026011',
            'nama_lengkap' => 'Fajar Nugroho',
            'email_kantor' => 'fajar.finance@novacore.co.id',
            'no_hp' => '08589877563',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1995-12-25',
            'alamat' => 'Jakarta',
            'agama' => 'Katolik',
            'npwp' => '12.345.678.9-011.000',
            'bpjs' => 'BPJS2026011',
            'tanggal_masuk' => '2019-01-20',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 5,
            'position_id' => 27,
            'nik' => 'EMP2026012',
            'nama_lengkap' => 'Gita Sari',
            'email_kantor' => 'gita.finance@novacore.co.id',
            'no_hp' => '08137863452',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1999-10-31',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-012.000',
            'bpjs' => 'BPJS2026012',
            'tanggal_masuk' => '2016-09-14',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        // ===========================
        // DIVISI MARKETING
        // ===========================

        [
            'division_id' => 3,
            'position_id' => 14,
            'nik' => 'EMP2026014',
            'nama_lengkap' => 'Hafiz Alfarizi',
            'email_kantor' => 'hafiz.marketing@novacore.co.id',
            'no_hp' => '08316054776',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1997-11-10',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-014.000',
            'bpjs' => 'BPJS2026014',
            'tanggal_masuk' => '2016-01-20',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 3,
            'position_id' => 15,
            'nik' => 'EMP2026015',
            'nama_lengkap' => 'Indah Permatasari',
            'email_kantor' => 'indah.marketing@novacore.co.id',
            'no_hp' => '089508784598',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2000-07-01',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-015.000',
            'bpjs' => 'BPJS2026015',
            'tanggal_masuk' => '2017-03-10',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 3,
            'position_id' => 16,
            'nik' => 'EMP2026016',
            'nama_lengkap' => 'Irfan Maulana',
            'email_kantor' => 'irfan.marketing@novacore.co.id',
            'no_hp' => '08597326512',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1994-03-18',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-016.000',
            'bpjs' => 'BPJS2026016',
            'tanggal_masuk' => '2018-06-15',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 3,
            'position_id' => 17,
            'nik' => 'EMP2026017',
            'nama_lengkap' => 'Jihan Rasyah Al Basyir',
            'email_kantor' => 'jihan.marketing@novacore.co.id',
            'no_hp' => '08123456789',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2005-12-26',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-017.000',
            'bpjs' => 'BPJS2026017',
            'tanggal_masuk' => '2020-03-10',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 3,
            'position_id' => 18,
            'nik' => 'EMP2026018',
            'nama_lengkap' => 'Kiki Pratama',
            'email_kantor' => 'kiki.marketing@novacore.co.id',
            'no_hp' => '08123456789',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1993-04-04',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-018.000',
            'bpjs' => 'BPJS2026018',
            'tanggal_masuk' => '2010-09-22',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 3,
            'position_id' => 19,
            'nik' => 'EMP2026019',
            'nama_lengkap' => 'Aulia Valentcia',
            'email_kantor' => 'aulia.marketing@novacore.co.id',
            'no_hp' => '087777575362',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2007-02-14',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-019.000',
            'bpjs' => 'BPJS2026019',
            'tanggal_masuk' => '2025-05-23',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        // ===========================
        // DIVISI DIGITAL CREATIVE
        // ===========================
        
        [
            'division_id' => 2,
            'position_id' => 5,
            'nik' => 'EMP2026020',
            'nama_lengkap' => 'Luthfi Ramadhan',
            'email_kantor' => 'luthfi.digital@novacore.co.id',
            'no_hp' => '08975890444',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2000-07-08',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-020.000',
            'bpjs' => 'BPJS2026020',
            'tanggal_masuk' => '2020-09-20',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 6,
            'nik' => 'EMP2026021',
            'nama_lengkap' => 'Nadia Putri',
            'email_kantor' => 'nadia.digital@novacore.co.id',
            'no_hp' => '082199766524',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1998-08-15',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-021.000',
            'bpjs' => 'BPJS2026021',
            'tanggal_masuk' => '2017-06-26',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 7,
            'nik' => 'EMP2026022',
            'nama_lengkap' => 'Bayu Putra',
            'email_kantor' => 'bayu.digital@novacore.co.id',
            'no_hp' => '089787560092',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2008-06-23',
            'alamat' => 'Jakarta',
            'agama' => 'Hindu',
            'npwp' => '12.345.678.9-022.000',
            'bpjs' => 'BPJS2026022',
            'tanggal_masuk' => '2025-02-28',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 8,
            'nik' => 'EMP2026023',
            'nama_lengkap' => 'Rizky Maulana',
            'email_kantor' => 'rizky.digital@novacore.co.id',
            'no_hp' => '088197065543',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1998-08-15',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-023.000',
            'bpjs' => 'BPJS2026023',
            'tanggal_masuk' => '2019-09-28',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 9,
            'nik' => 'EMP2026024',
            'nama_lengkap' => 'Siti Nurhaliza',
            'email_kantor' => 'siti.digital@novacore.co.id',
            'no_hp' => '08897786346',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1990-03-05',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-024.000',
            'bpjs' => 'BPJS2026024',
            'tanggal_masuk' => '2016-10-11',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 10,
            'nik' => 'EMP2026025',
            'nama_lengkap' => 'Ahmad Fauzi',
            'email_kantor' => 'ahmad.digital@novacore.co.id',
            'no_hp' => '081234567890',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1993-11-08',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-025.000',
            'bpjs' => 'BPJS2026025',
            'tanggal_masuk' => '2011-05-19',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 11,
            'nik' => 'EMP2026026',
            'nama_lengkap' => 'Putri Lestari',
            'email_kantor' => 'putri.digital@novacore.co.id',
            'no_hp' => '088976530756',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1995-04-16',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-026.000',
            'bpjs' => 'BPJS2026026',
            'tanggal_masuk' => '2020-07-01',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 12,
            'nik' => 'EMP2026027',
            'nama_lengkap' => 'Rizka Amelia',
            'email_kantor' => 'rizka.digital@novacore.co.id',
            'no_hp' => '081157634456',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1999-01-01',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-027.000',
            'bpjs' => 'BPJS2026027',
            'tanggal_masuk' => '2023-09-04',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],

        [
            'division_id' => 2,
            'position_id' => 13,
            'nik' => 'EMP2026028',
            'nama_lengkap' => 'Dewi Sartika',
            'email_kantor' => 'dewi.digital@novacore.co.id',
            'no_hp' => '081234567892',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1990-06-16',
            'alamat' => 'Jakarta',
            'agama' => 'Islam',
            'npwp' => '12.345.678.9-028.000',
            'bpjs' => 'BPJS2026028',
            'tanggal_masuk' => '2015-08-08',
            'status_pegawai' => 'Tetap',
            'is_active' => true,
            'foto' => null,
        ],
    ];

    foreach ($employees as $employee) {
        $position = Position::query()->find($employee['position_id']);

        $employee['division_id'] = $position?->division_id ?? $employee['division_id'];

        $user = User::query()->firstOrCreate(
            ['email' => $employee['email_kantor']],
            [
                'name' => $employee['nama_lengkap'],
                'password' => Hash::make('password'),
            ]
        );

        $employee['user_id'] = $user->id;

        Employee::query()->firstOrCreate(
            ['nik' => $employee['nik']],
            $employee
        );
    }
    }
}